services:
  rubik-algorithm:
    image: lscr.io/linuxserver/nginx:1.30.4
    container_name: rubik-algorithm
    restart: unless-stopped
    environment:
      - PUID=950
      - PGID=950
      - TZ=Europe/Paris
    volumes:
      - ./site:/config/www:ro
    ports:
      - "4000:80"
    tmpfs:
      - /run:exec
      - /tmp
    read_only: true
