site_name: Rubik's Cube Algorithms
site_url: https://guillaumelepape.github.io/rubik-algorithm/

theme:
  name: material
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - toc.follow

plugins:
  - search
  - site-urls
  - macros:
      module_name: macros

nav:
  - Home: index.md
  - COFP:
      - '<img src="/rubik-algorithm/images/f2l/menu_icon.png" width="20"> F2L': f2l.md
      - '<img src="/rubik-algorithm/images/oll/menu_icon.png" width="20"> OLL': oll.md
      - '<img src="/rubik-algorithm/images/pll/menu_icon.png" width="20"> PLL': pll.md
