site_name: Rubik's Cube Algorithms
site_url: https://guillaumelepape.github.io/rubik-algorithm/

theme:
  name: material
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: light blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - toc.follow
    - content.tabs.link

plugins:
  - search
  - site-urls
  - macros:
      module_name: macros

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true

nav:
  - Home: index.md
  - COFP:
      - '<img src="/rubik-algorithm/images/f2l/menu_icon.png" width="20"> F2L': f2l.md
      - '<img src="/rubik-algorithm/images/oll/menu_icon.png" width="20"> OLL': oll.md
      - '<img src="/rubik-algorithm/images/pll/menu_icon.png" width="20"> PLL': pll.md
