name: 📦 Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Build website
        run: uv run mkdocs build

      - name: Deploy to release/main
        run: |-
          # Create worktree for release
          git fetch origin
          git worktree add /tmp/release origin/release/main

          # Clean previous contents
          rm -rf /tmp/release/*

          # Copy new build
          cp -r site /tmp/release/
          cp docker-compose.yml /tmp/release/

          cd /tmp/release

          git add .
          git commit -m "Update site" || echo "No changes to commit"
          git push origin release/main
