name: 🧪 Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-lock-file:
    name: Check lock file
    runs-on: ubuntu-latest

    env:
      python-version: "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Check lock file
        run: uv lock --check

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    env:
      python-version: "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Run test
        run: uv run pytest --cov=rubik_algorithm --cov=tests --cov-report=xml --cov-config=pyproject.toml -vv
        if: ${{ always() }}

  build-website:
    name: Build website
    runs-on: ubuntu-latest

    env:
      python-version: "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build website
        run: uv run mkdocs build --strict
